services:

  rabbitmq:
    image: rabbitmq:4.0.4
    ports:
      - ${DOCKER_RABBITMQ_CLIENT_PORT:-5672}:5672
      - ${DOCKER_RABBITMQ_MANAGEMENT_PORT:-15672}:15672
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    restart: on-failure

  localstack:
    image: localstack/localstack:4.10.0
    network_mode: bridge
    hostname: localstack
    ports:
      - '127.0.0.1:4566:4566' # LocalStack Gateway
      - '127.0.0.1:4510-4559:4510-4559' # external services port range
    environment:
      - SERVICES=sns,sqs,s3,sts
      - DEBUG=0
      - DATA_DIR=${DATA_DIR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_HOST=localstack
    #      - LOCALSTACK_API_KEY=someDummyKey
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/var/log/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: on-failure

  redis:
    image: redis:6.2.7-alpine
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/redis/data:cached
    restart: on-failure

  kafka:
    image: apache/kafka:3.7.1
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: LOCAL://0.0.0.0:9092,DOCKER://kafka:9093,CONTROLLER://localhost:9094
      KAFKA_ADVERTISED_LISTENERS: LOCAL://localhost:9092,DOCKER://kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: LOCAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,LOCAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
    restart: on-failure

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: Local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    restart: on-failure

volumes:
  rabbit_data:
    driver: local
  redis_data:
    driver: local
