services:

  kafka:
    image: apache/kafka:3.7.1
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: LOCAL://0.0.0.0:9092,DOCKER://kafka:9093,CONTROLLER://localhost:9094
      KAFKA_ADVERTISED_LISTENERS: LOCAL://localhost:9092,DOCKER://kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: LOCAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,LOCAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 6
    healthcheck:
      test: /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 15s
    restart: on-failure

  cockroachdb:
    image: cockroachdb/cockroach:latest-v25.1
    command: start-single-node --insecure
    ports:
      - 26257:26257
      - 8181:8080
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      test: curl -f http://localhost:8080/health?ready=1 || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: on-failure

  crdb-init:
    image: cockroachdb/cockroach:latest-v25.1
    volumes:
      - ./scripts/init-crdb.sh:/init-crdb.sh
    entrypoint: ["/bin/bash", "/init-crdb.sh"]
    depends_on:
      cockroachdb:
        condition: service_healthy
    restart: "no"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: LoadTest
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    restart: on-failure
